// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvrKgRLA_pu7A3J9DtLvrCoIeKGC4qP-I',
    appId: '1:934750627493:web:1e70aac2e7ddfa8f948f4c',
    messagingSenderId: '934750627493',
    projectId: 'teste-firebase-82a3d',
    authDomain: 'teste-firebase-82a3d.firebaseapp.com',
    storageBucket: 'teste-firebase-82a3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX20DGi6gitfG9wKIpy4QQn6ctD9DpVNI',
    appId: '1:934750627493:android:58c856306280e364948f4c',
    messagingSenderId: '934750627493',
    projectId: 'teste-firebase-82a3d',
    storageBucket: 'teste-firebase-82a3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKICa_3f0Cn5NTfTTGul1Uel9xAs8nUMk',
    appId: '1:934750627493:ios:aa3b1cf1b8d1ba35948f4c',
    messagingSenderId: '934750627493',
    projectId: 'teste-firebase-82a3d',
    storageBucket: 'teste-firebase-82a3d.appspot.com',
    iosClientId: '934750627493-bs3d30kamjlofvmjf5gju4te52rf98vl.apps.googleusercontent.com',
    iosBundleId: 'com.example.zapzap2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKICa_3f0Cn5NTfTTGul1Uel9xAs8nUMk',
    appId: '1:934750627493:ios:aa3b1cf1b8d1ba35948f4c',
    messagingSenderId: '934750627493',
    projectId: 'teste-firebase-82a3d',
    storageBucket: 'teste-firebase-82a3d.appspot.com',
    iosClientId: '934750627493-bs3d30kamjlofvmjf5gju4te52rf98vl.apps.googleusercontent.com',
    iosBundleId: 'com.example.zapzap2',
  );
}
